arent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from .views import Home, redirectKeHome

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mitra/', include('mitra.urls', namespace='mitra')),
    path('', redirectKeHome, name='redirectKeHome'),
    path('page/<int:page>', Home.as_view(), name='home')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mitra/urls.py
from django.urls import path

from .views import (
    loginView, 
    registerView, 
    logoutView, 
    tambahIklan, 
    UpdateUser,
    UpdateIklan,
    ManageIklan,
    DeleteIklan,
    DetailIklan,
)
app_name = 'mitra'
urlpatterns = [
    path('login', loginView, name='login'),
    path('register', registerView, name='registrasi'),
    path('logout', logoutView, name='logout'),
    path('tambahIklan', tambahIklan, name='tambahIklan'),
    path('updateUser/<int:pk>', UpdateUser.as_view(), name='updateUser'),
    path('updateIklan/<int:pk>', UpdateIklan.as_view(), name='updateIklan'),
    path('iklanSaya', ManageIklan.as_view(), name='iklanSaya'),
    path('deleteIklan/<int:pk>', DeleteIklan.as_view(), name='deleteIklan'),
    path('detailIklan/<str:slug>', DetailIklan.as_view(), name='detailIklan'),
]

mitra/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User 
from django.urls import reverse
# Create your models here.

class AkunMitra(models.Model):
    pilihanprovinsi = (
        ('Aceh','Aceh'),
        ('Bali','Bali'),
        ('Banten','Banten'),
        ('Bengkulu','Bengkulu'),
        ('Gorontalo','Gorontalo'),
        ('D.I Yogyakarta','D.I Yogyakarta'),
        ('D.K.I Jakarta','D.K.I Jakarta'),
        ('Jambi','Jambi'),
        ('Jawa Barat','Jawa Barat'),
        ('Jawa Tengah','Jawa Tengah'),
        ('Jawa Timur','Jawa Timur'),
        ('Kalimantan Barat','Kalimantan Barat'),
        ('Kalimantan Selatan','Kalimantan Selatan'),
        ('Kalimantan Tengah','Kalimantan Tengah'),
        ('Kalimantan Timur','Kalimantan Timur'),
        ('Kalimantan Utara','Kalimantan Utara'),
        ('Kep. Bangka Belitung','Kep. Bangka Belitung'),
        ('Kep. Riau','Kep. Riau'),
        ('Lampung','Lampung'),
        ('Maluku','Maluku'),
        ('Maluku Utara','Maluku Utara'),
        ('Nusa Tenggara Barat','Nusa Tenggara Barat'),
        ('Nusa Tenggara Timur','Nusa Tenggara Timur'),
        ('Papua','Papua'),
        ('Papua Barat','Papua Barat'),
        ('Riau','Riau'),
        ('Sulawesi Barat','Sulawesi Barat'),
        ('Sulawesi Selatan','Sulawesi Selatan'),
        ('Sulawesi Tengah','Sulawesi Tengah'),
        ('Sulawesi Tenggara','Sulawesi Tenggara'),
        ('Sulawesi Utara','Sulawesi Utara'),
        ('Sumatera Barat','Sumatera Barat'),
        ('Sumatera Selatan','Sumatera Selatan'),
        ('Sumatera Utara','Sumatera Utara'),
    )


    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nama = models.CharField(max_length=50)
    provinsi = models.CharField(
        max_length=50,
        choices=pilihanprovinsi,
    )
    alamat = models.TextField()
    no_hp = models.CharField(max_length=15)
    photo = models.ImageField(upload_to='mitra/poto_profil/%Y/%m/%d/')

    def __str__(self):
        return '{}. {}'.format(self.id, self.user.username)

    def get_absolute_url(self):
        
        return reverse('home') #kwargs={'pk': self.pk})

class Iklan(models.Model):
    pilihanJenisKendaraan = (
        ('sepeda_motor', 'Sepeda Motor'),
        ('mobil', 'Mobil')
    )
    mitra = models.ForeignKey(User, on_delete=models.CASCADE)
    gambar = models.ImageField(upload_to='mitra/iklan/%Y/%m/%d/')
    judul = models.CharField(max_length=150)
    published = models.DateField(auto_now_add=True)
    jenis_kendaraan = models.CharField(max_length=20, choices=pilihanJenisKendaraan)
    merk = models.CharField(max_length=30)
    tipe_kendaraan = models.CharField(max_length=30)
    harga_sewa = models.CharField(max_length=50)
    deskripsi_lain = models.TextField()
    slug = models.SlugField(blank=True, editable=False)

    def simpanHarga(self, hargaInput):
        listHarga = []
        for i in range(0,len(hargaInput),(1)):
            listHarga.append(hargaInput[i])

        for i in range(len(listHarga),0,-3):
            listHarga.insert(i,'.')
        del listHarga[(len(listHarga)-1)]
        hargaOutput = ''.join(listHarga)
        return hargaOutput

    
    def save(self):
        self.harga_sewa = self.simpanHarga(self.harga_sewa)
        self.slug = slugify((self.mitra.akunmitra.nama, self.judul))
        super().save()

    def get_absolute_url(self):
        
        return reverse('home') #kwargs={'pk': self.pk})
    # def get_absolute_url(self):
    #     return reverse('artikel:artikeldetail', kwargs={'slug': self.slug})

    def __str__(self):
        return '{}. {} | {}'.format(self.id, self.mitra.akunmitra.nama, self.judul)

    class Meta:
        ordering = ['-id']

mitra/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import AkunMitra, Iklan

class AkunMitraForm(forms.ModelForm):
    class Meta:
        model = AkunMitra
        fields = [
            'nama',
            'provinsi',
            'alamat',
            'no_hp',
            'photo',
        ]
        widgets = {
            'nama':forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Nama lengkap Anda',
                },
            ),
            'provinsi':forms.Select(
                attrs={
                    'class':'form-control',
                },
            ),
            'no_hp':forms.NumberInput(
                attrs={
                    'class':'form-control',
                },
            ),
            #'photo':forms.ImageField(),
            'alamat':forms.Textarea(
                attrs={
                    'class':'form-control'
                }
            )
        }

class PilihProvinsiForm(forms.ModelForm):
    class Meta:
        model = AkunMitra
        fields = [
            'provinsi'
        ]
        widgets = {
            'provinsi':forms.Select(
                attrs={
                    'class':'form-control',
                },
            ),
        }
        
class UserMitra(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
        ]
        widgets= {
            'email':forms.EmailInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Email Anda',
                },
            ),
            'password':forms.PasswordInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Password Anda',
                },
            ),
            'username':forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Username Anda',
                },
            ),
        }

class IklanForm(forms.ModelForm):
    class Meta:
        model = Iklan
        fields = [
            'judul',
            'jenis_kendaraan',
            'merk',
            'tipe_kendaraan',
            'harga_sewa',
            'deskripsi_lain',
            'gambar',
        ]
        widgets = {
            'judul':forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Buat judul semenarik mungkin',
                },
            ),
            'harga_sewa':forms.NumberInput(
                attrs={
                    'class':'form-control',
                }
            ),
            'jenis_kendaraan':forms.Select(
                attrs={
                    'class':'form-control',
                },
            ),
            'merk':forms.TextInput(
                attrs={
                    'class':'form-control',
                },
            ),
            'tipe_kendaraan':forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'ex:supra, avanza dll',
                },
            ),
            'deskripsi_lain':forms.Textarea(
                attrs={
                    'class':'form-control',
                },
            ),
            'gambar':forms.FileInput(
                attrs={
                    'class':'form-control',
                }
            )
        }
    

mitra/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import FormView, ListView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy

# Create your views here.

from .models import AkunMitra, Iklan
from .forms import AkunMitraForm, UserMitra, IklanForm

def loginView(request):

    if request.method == 'POST':
        username_login = request.POST['username']
        password_login = request.POST['password']
        user = authenticate(request, username=username_login,password=password_login)
        if user is not None:
            login(request, user)
            return redirect('redirectKeHome')
        else:
            return redirect('mitra:login')

    return render(request, 'mitra/login.html')

def registerView(request):
    registered = False
    user_mitra = UserMitra(request.POST or None)
    profile_mitra = AkunMitraForm(request.POST or None, request.FILES)
    if request.method == 'POST':
        if user_mitra.is_valid() and profile_mitra.is_valid():
            user = user_mitra.save()
            user.set_password(user.password)
            user.save()
            profile = profile_mitra.save(commit=False)
            profile.user = user
            if 'photo' in request.FILES:
                profile.photo = request.FILES['photo']
            profile.save()
            registered =True
            new_user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
            login(request, new_user)
            return redirect('redirectKeHome')

    context = {
        'profileMitraForm':profile_mitra,
        'userMitraForm':user_mitra,
        'page_title':'Registrasi Mitra',
        'registered':registered,
        # 'error1':user_mitra.errors,
        # 'error2':profile_mitra.errors,
    }

    return render(request, 'mitra/registrasi.html', context)

def logoutView(request):
    if request.method == 'POST':
        if request.POST['logout'] == 'ya':
            logout(request)
            return redirect('redirectKeHome')
        elif request.POST['logout'] == 'tidak':
            return redirect('redirectKeHome')

    context = {
        'page_title':'Logout Confirmation'
    }

    return render(request, 'mitra/logout.html', context)

class UpdateUser(UpdateView):
    model = AkunMitra
    template_name = 'mitra/updateUser.html'
    form_class = AkunMitraForm
    success_url = reverse_lazy('redirectKeHome')
    extra_context = {
        'page_title':'Edit Akun',
    }

    # def get_object(self, *args, **kwargs, queyset=None):
    #     obj =  super().get_object()
    #     if not obj.mitra == self.request.user:
    #         return redirect(obj)
    #     return obj

    def dispatch(self, request, *args, **kwargs):#ini untuk ownership object/ jadi cuma yang create object ini yang bisa edit
        obj =  super().get_object()
        if not obj.user == self.request.user:
            return redirect(obj)
        return super().dispatch(request, *args, **kwargs)


    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

def tambahIklan(request):
    iklan = IklanForm(request.POST or None, request.FILES)
    if request.method == 'POST':
        if iklan.is_valid():
            iklan_save =  iklan.save(commit=False)
            iklan_save.mitra = request.user
            if 'gambar' in request.FILES:
                iklan_save.gambar =  request.FILES['gambar']
            iklan_save.save()
            return redirect('redirectKeHome')
    context = {
        'page_title':'Tambah Iklan',
        'iklanForm':iklan,
    }
    return render(request, 'mitra/tambahIklan.html', context)

class UpdateIklan(UpdateView):
    model = Iklan
    template_name = 'mitra/updateUser.html'
    form_class = IklanForm
    success_url = reverse_lazy('mitra:iklanSaya')
    extra_context = {
        'page_title':'Edit Iklan',
    }

    def dispatch(self, request, *args, **kwargs):#ini untuk ownership object/ jadi cuma yang create object ini yang bisa edit
        obj =  super().get_object()
        if not obj.mitra == self.request.user:
            return redirect(obj)
        return super().dispatch(request, *args, **kwargs)


    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context
    

class ManageIklan(ListView):
    template_name = 'mitra/iklanSaya.html'
    model = Iklan
    context_object_name = 'iklan_list'
    ordering_by = ['-id']
    paginate_by = 25
    def get_context_data(self,*args, **kwargs):
        self.kwargs.update({
            'page_title':'Iklan Saya'
        })
        kwargs = self.kwargs
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        print(self.request.user.id)
        self.queryset = self.model.objects.filter(mitra=self.request.user.id)
        return super().get_queryset()


class DeleteIklan(DeleteView):
    model = Iklan
    template_name = 'mitra/iklanDeleteConfirm.html'
    success_url = reverse_lazy('mitra:iklanSaya')

class DetailIklan(DetailView):
    template_name = 'mitra/iklanDetail.html'
    model = Iklan

# def cariIklan(request, cari):
#     pencarian = cari.replace('%20',' ')
#     tampil = Iklan.objects.filter(judul__contains=pencarian)
#     context = {
#         'iklan_list':tampil,
#         'page_title':'Home',
#     }

#     return render(request, 'home.html', context)

mitra/templates/mitra/iklanDeleteConfirm.html
{% extends 'base.html' %}


{% block contents %}
    <p>Apakah Anda yakin ingin menghapus iklan ini {{obj}}</p>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Ya</button>
        <a href="{% url 'mitra:iklanSaya' %}" class="btn btn-secondary">Tidak</a>
    </form>
{% endblock contents %}
    

mitra/templates/mitra/iklanDetail.html
{% extends 'base.html' %}


{% block contents %}
<div class="container">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="/media/{{object.gambar}}" class="d-block ml-auto mr-auto" style="height: 400px;"alt="...">
            </div>
        </div>
    </div>
</div>

    <p>{{object.judul}}</p>
    <p>{{object.deskripsi_lain|linebreaks}}</p>
{% endblock contents %}
    

mitra/templates/mitra/iklanSaya.html
{% extends 'base.html' %}


{% block contents %}
    <h1>{{page_title}}</h1>
    
    <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Judul Iklan</th>
                <th scope="col">Harga Sewa per Hari</th>
                <th scope="col">Jenis Kendaraan</th>
                <th scope="col">Tipe Kendaraan</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
        {% for iklan in iklan_list %}
            <tbody>
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{iklan.judul}}</td>
                <td>{{iklan.harga_sewa}}</td>
                <td>{{iklan.jenis_kendaraan}}</td>
                <td>{{iklan.tipe_kendaraan}}</td>
                <td>
                    <a href="{% url 'mitra:detailIklan' iklan.slug %}" class="btn btn-warning">Lihat Iklan</a>
                    <a href="{% url 'mitra:deleteIklan' iklan.pk %}" class="btn btn-danger">Hapus Iklan</a>
                    <a href="{% url 'mitra:updateIklan' iklan.pk %}" class="btn btn-info">Edit Iklan</a>
                </td>
              </tr>
            </tbody>
        {% endfor %}
          </table>
        <!-- Batas -->
    <br><br>
    <a href="{% url 'mitra:tambahIklan' %}" class="btn btn-primary ml-4">Tambah Iklan</a>
        
{% endblock contents %}
    

mitra/templates/mitra/login.html
{% extends 'base.html' %}


{% block contents %}
<form method="POST" class="col-lg-4">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Username</label>
      <input type="text" class="form-control" id="username" name="username" placeholder="Username">
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" class="form-control" id="password" name="password" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<h1>{{page_title}}</h1>
{% endblock contents %}
    

mitra/templates/mitra/logout.html
{% extends 'base.html' %}


{% block contents %}

    <p>Apakah anda yakin untuk logout sebagai {{user}}</p>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="logout" value="ya">
        <input type="submit" name="logout" value="tidak">
    </form>

{% endblock contents %}

mitra/templates/mitra/registrasi.html
{% extends 'base.html' %}


{% block contents %}
{{error1}}
{{error2}}
<div class="container pb-5 shadow">
    <h1>{{page_title}}</h1>
    <form method="POST" class="col-lg-8" enctype="multipart/form-data">
        {% csrf_token %}
        
        {% for user in userMitraForm %}
            <div class="form-group">
                {{user.label}}
                {{user}}
            </div>
        {% endfor %}
        
        {% for profile in profileMitraForm %}
            <div class="form-group">
                {{profile.label}}
                {{profile}}
            </div>
        {% endfor %}
            
        <button type="submit" class="btn btn-primary col-sm-4 mt-4">Daftar</button>
            
    </form>

    <!-- <form method="POST">
        {{userMitraForm.as_table}}
    </form> -->
</div>
{% endblock contents %}
    

mitra/templates/mitra/tambahIklan.html
{% extends 'base.html' %}


{% block contents %}
<div class="container">
    <form class="col-lg-8 pb-5" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for component in iklanForm %}
            <div class="form-group">
                {{component.label}}
                {{component}}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Tambah</button>
    </form>
</div>
{% endblock contents %}
    

mitra/templates/mitra/updateUser.html
{% extends 'base.html' %}

{% block contents %}
<div class="container">
    <h1>Edit Akun</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        {% for component in form %}
            <div class="form-gorup">
                {{component.label}}
                {{component}}
            </div>
        {% endfor %}
            
        <button type="submit" class="btn btn-primary">Edit</button>
    </form>
</div>
{% endblock contents %}
    